npm install -g yo
npm install -g grunt-cli
npm install -g bower
npm install -g jshint
npm install -g coffee-script
npm install -g less
npm install -g gulp
npm install -g browserify
npm install -g generator-webapp
npm install -g generator-gulp-webapp
