# TODO (h4w5) get default settings from Ubuntu installs and see what needs to be added here (beyond the standard profile)

# If not running interactively, don't do anything
case $- in
     *i*) ;;
       *) return;;
esac

[ -n "$PS1" ] && source ~/.bash_profile
