# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias reload="clear; source ~/.zshrc"

# More verbose commands
# alias cp='cp -iv'
# alias mv='mv -iv'
# alias rm='rm -iv'
# alias mkdir='mkdir -pv'
# alias h='history'

# Hide/show desktop files
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# Hide/show hidden files in Finder
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
alias showfiles="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
  atom
  bower
  brew
  brew-cask
  bundler
  common-aliases
  coffee
  colorize
  gem
  git
  git-hubflow
  github
  heroku
  jsontools
  node
  npm
  osx
  postgres
  rails
  rbenv
  redis-cli
  ruby
  sublime
  terminalapp
  thor
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# eval "$(rbenv init -)"

# =================
# rbenv
# =================
# start rbenv (our Ruby environment and version manager) on open
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# rbenv
PATH="$HOME/.rbenv/shims:$PATH"
# Node Package Manager
PATH="/usr/local/share/npm/bin:$PATH"
# Homebrew
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
# Heroku Toolbelt
PATH="/usr/local/heroku/bin:$PATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export EDITOR='subl -w'
# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"
# Note
# chsh -s `which bash` will toggle the default shell
