# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# ---------------------------------------------------------------------------
# ZSH Settings
# ---------------------------------------------------------------------------
ZSH_THEME="ys"
COMPLETION_WAITING_DOTS="true"

# ---------------------------------------------------------------------------
# exports
# ---------------------------------------------------------------------------
# You may need to manually set your language environment
export LANG=en_US.UTF-8
export EDITOR='subl -w'
# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"
# Note
# chsh -s `which bash` will toggle the default shell

# ---------------------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------------------

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
  atom
  bower
  brew
  brew-cask
  bundler
  common-aliases
  coffee
  colorize
  gem
  git
  git-hubflow
  github
  heroku
  jsontools
  node
  npm
  osx
  postgres
  rails
  rbenv
  redis-cli
  ruby
  sublime
  terminalapp
  thor
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# ---------------------------------------------------------------------------
# rbenv
# ---------------------------------------------------------------------------
# start rbenv (our Ruby environment and version manager) on open
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PATH="$HOME/.rbenv/shims:$PATH"
# Node Package Manager
PATH="/usr/local/share/npm/bin:$PATH"
# Homebrew
PATH="/usr/local/bin:/usr/local/sbin:$PATH"
# Heroku Toolbelt
PATH="/usr/local/heroku/bin:$PATH"
# Coreutils
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# ---------------------------------------------------------------------------
# Aliases
# ---------------------------------------------------------------------------
alias reload="clear; source ~/.zshrc"
# Hide/show desktop files
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# Hide/show hidden files in Finder
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
alias showfiles="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"
