# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

alias reload="clear; source ~/.zshrc"

# More verbose commands
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias mkdir='mkdir -pv'
alias h='history'

# Hide/show desktop files
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
# Hide/show hidden files in Finder
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
alias showfiles="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(atom brew brew-cask bundler colorize gem git git-hubflow git-prompt github heroku jsontools node npm osx postgres rails rbenv ruby sublime terminalapp zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# PATH="~/.rbenv/shims:\
# /usr/local/heroku/bin:\
# /usr/local/sbin:\
# /usr/local/bin:\
# /usr/local/share/npm/bin:\
# ~/.rbenv/shims:\
# /usr/local/heroku/bin:\
# /usr/local/sbin:\
# /usr/local/bin:\
# /usr/local/share/npm/bin:\
# /usr/bin:\
# /bin:\
# /usr/sbin:\
# /sbin:\
# /usr/local/bin:\
# /opt/X11/bin"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
LANG=en_US.UTF-8

# for Homebrew installed rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
